// Dependencies
import Head from "next/head";
import { Input, Button } from "@nextui-org/react";
import Swal from 'sweetalert2';
// Utils
import FileToBase64 from "../utils/FileToBase64";

export default function Home() {

  const handleImportFile = async (e) => {
    e.preventDefault();
    const file = e.target.file.files[0];
    // validate file type are csv
    if (file.type !== "text/csv") {
      Swal.fire(
        'Archivo no valido',
        'Solo se aceptan archivos .csv, por favor intenta de nuevo',
        'warning'
      )
    }
    // convert file to base64
    const base64 = await FileToBase64(file);
    console.log(base64)
  };

  return (
    <>
      <Head>
        <title>Mineria de Datos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center min-w-screen min-h-screen">
        <form onSubmit={handleImportFile} className="bg-white shadow-xl shadow-white/20 p-4 rounded-xl text-black flex flex-col items-center gap-2">
          <p className="text-xl">Importa el archivo de tu dataset</p>
          <Input type="file" name="file" id="" />
          <Button type="submit"> Importar </Button>
        </form>
      </main>
    </>
  );
}
